### ISSUE TITLE
SSLHandshakException

### ISSUE THREAD

**Issue by nishashirawala** [Yelp/yelp-android#31]
I would like to create a sample using yelp-android, but I get following exception
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

How to know or get certification path?

**Comment by tzuhanwu** [comment]
Hi @nishashirawala, could you provide the stacktrace you got? And also, which version of Android you are using?

**Comment by nishashirawala** [comment]
Here is the stacktrace. I am using android 6.0. However, even If I just run the service to use yelp-android and get search results, it gives me exception w/o android. 
Please help.
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
   at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
   at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:195)
   at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:148)
   at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
   at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
   at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
   at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
   at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
   at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
   at okhttp3.RealCall.getResponse(RealCall.java:240)
   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
   at com.yelp.clientlib.exception.ErrorHandlingInterceptor.intercept(ErrorHandlingInterceptor.java:42)
   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
   at se.akerfeldt.okhttp.signpost.SigningInterceptor.intercept(SigningInterceptor.java:46)
   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
   at okhttp3.RealCall.execute(RealCall.java:57)
   at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
   at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
   at sample.yelp.com.yelprestaurantapp.RestaurantService.makeYelpRequest(RestaurantService.java:38)
   at sample.yelp.com.yelprestaurantapp.RestaurantServiceAsyncTask.doInBackground(RestaurantServiceAsyncTask.java:13)

**Comment by tzuhanwu** [comment]
@nishashirawala, you should be able to see your Trusted Credentials in **"Settings"**->**"Security"**->**"Trusted credentials"**. **"DigiCert Global Root CA"** should be on the list, and you can get it from [DigiCert website](https://www.digicert.com/digicert-root-certificates.htm) if you don't see it there.

Yelp uses a certificate issued by Digicert, you can find it by going to https://www.yelp.com and click on the lock icon on the left of the url bar, you should be able to find the certificate Yelp uses somewhere there depends on the browser you use. 

I have an emulator with Android 6.0 has **DigiCert Global Root CA** listed on the list by default, and I got similar error message when I disable it.

**Comment by nishashirawala** [comment]
@tzuhanwu - Thanks for your response. It has something to do with security at my office. It works perfectly fine at my home's internet connection.

**Comment by tzuhanwu** [comment]
Glad you figured that out!
